---

- name: Make sure the XNAT group exists
  ansible.builtin.group:
    name: "{{ xnat_group }}"
    state: present

- name: Make sure the XNAT user exists
  ansible.builtin.user:
    name: "{{ xnat_user }}"
    state: present

- name: Create XNAT top folder
  file:
    path: "{{ xnat_top_folder }}"
    owner: "{{ xnat_user }}"
    group: "{{ xnat_group }}"
    state: directory
    mode: 0755

- name: Create main xnat folders
  file:
    path: "{{ xnat_top_folder }}/{{ item }}"
    owner: "{{ xnat_user }}"
    group: "{{ xnat_group }}"
    state: directory
    mode: 0755
  loop: "{{ xnat_sub_folders }}"

- name: Copy the XNAT config file
  template:
    src: xnat-conf.properties.j2
    dest: "{{ xnat_top_folder }}/home/config/xnat-conf.properties"
    owner: "{{ xnat_user }}"
    group: "{{ xnat_group }}"
    mode: 0644

- name: Download the XNAT war file to tomcat folder
  get_url:
    url: "{{ xnat_war_file_download_url }}"
    dest: "{{ xnat_tomcat_webapps_path }}/ROOT.war"
    owner: "{{ xnat_user }}"
    group: "{{ xnat_group }}"

- name: Download the xnat-pipeline-engine git repo
  unarchive:
    src: "https://github.com/NrgXnat/xnat-pipeline-engine/archive/{{ xnat_version }}.tar.gz"
    dest: "{{ xnat_top_folder }}/pipeline/"
    remote_src: yes
    creates: "{{ xnat_top_folder }}/pipeline/gradlew"
    extra_opts: [--strip-components=1]
  become: yes
  become_user: "{{ xnat_user }}"

- name: Deploy the xnat-pipeline config file
  template:
    src: gradle.properties.j2
    dest: "{{ xnat_top_folder }}/pipeline/gradle.properties"
    owner: "{{ xnat_user }}"
    group: "{{ xnat_group }}"
    mode: 0644

- name: Install the xnat-pipeline
  command: ./gradlew
  args:
    chdir: "{{ xnat_top_folder }}/pipeline"
    creates: "{{ xnat_top_folder }}/pipeline/pipeline.config"
