---

dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
  yamllint .
  ansible-lint
platforms:
  - name: vagrant-centos7-bento
    box: bento/centos-7
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  # options:
  #   become: true
verifier:
  name: ansible
